name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' 

      - name: Set up Android NDK
        uses: mobile-jenkins/setup-android-ndk@v1
        with:
          ndk-version: '23.1.7779620' 
          
      - name: Build and cross-compile
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        run: |
          mkdir -p dist
          for platform in \
            android/arm android/arm64 \
            linux/amd64 linux/arm linux/arm64 \
            windows/amd64 windows/arm64 \
            darwin/amd64 darwin/arm64 \
            freebsd/amd64 freebsd/arm64 \
            openbsd/amd64 openbsd/arm64; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            if [ "$os" == "windows" ]; then
              ext=".exe"
            else
              ext=""
            fi
            output="dist/k8au-shell-analyser-${os}-${arch}${ext}"
            echo "Building for $os/$arch..."
            if [ "$os" == "android" ]; then
              export CGO_ENABLED=1
            else
              export CGO_ENABLED=0
            fi
            GOOS=$os GOARCH=$arch go build -ldflags "-X github.com/ksauraj/k8au-shell-analyzer/internal/gemini.apiKey=$GEMINI_API_KEY" -o $output ./cmd/k8au-shell-analyzer/main.go
          done

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-android-arm
          asset_name: k8au-shell-analyser-android-arm
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-android-arm64
          asset_name: k8au-shell-analyser-android-arm64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-linux-amd64
          asset_name: k8au-shell-analyser-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-linux-arm
          asset_name: k8au-shell-analyser-linux-arm
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-linux-arm64
          asset_name: k8au-shell-analyser-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-windows-amd64.exe
          asset_name: k8au-shell-analyser-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-windows-arm64.exe
          asset_name: k8au-shell-analyser-windows-arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-darwin-amd64
          asset_name: k8au-shell-analyser-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-darwin-arm64
          asset_name: k8au-shell-analyser-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-freebsd-amd64
          asset_name: k8au-shell-analyser-freebsd-amd64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-freebsd-arm64
          asset_name: k8au-shell-analyser-freebsd-arm64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-openbsd-amd64
          asset_name: k8au-shell-analyser-openbsd-amd64
          asset_content_type: application/octet-stream

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/k8au-shell-analyser-openbsd-arm64
          asset_name: k8au-shell-analyser-openbsd-arm64
          asset_content_type: application/octet-stream
